eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 8100

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: conversation-service
  data:
    mongodb:
      database: conversation_service
      uri: mongodb+srv://admin:admin@java-cluster.dydtuf8.mongodb.net/

springdoc:
  packages-to-scan:
    com.trvankiet.app
  api-docs:
    path: /v3/api-docs/conversation-service

#management:
#  tracing:
#    sampling:
#      probability: 1.0
